services:
  modulebankproject:
    image: ${DOCKER_REGISTRY-}modulebankproject
    build:
      context: .
      dockerfile: ModulebankProject/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
    depends_on:
      - keycloak
      - postgres
      - rabbitmq
    ports:
      - "80:8080"
    networks:
      - my-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: Keycloak
    command: start-dev
    networks:
      - my-network
    environment:
        - KC_HEALTH_ENABLED=true
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
        - ./.containers/identity:/opt/keycloak/data
    ports:
        - 18080:8080
  
  postgres:
    image: postgres:latest
    container_name: Postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: ModulebankAccountsDb
    ports:
      - "5433:5432"
    volumes:
      - ./.containers/postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./.containers/rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
