services:
  modulebankproject:
    image: ${DOCKER_REGISTRY-}modulebankproject
    build:
      context: .
      dockerfile: ModulebankProject/Dockerfile
    depends_on:
      - keycloak
    ports:
      - "80:8080"
    networks:
      - my-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: Keycloak
    command: start-dev
    networks:
      - my-network
    environment:
        - KC_HEALTH_ENABLED=true
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
        - ./.containers/identity:/opt/keycloak/data
    ports:
        - 18080:8080
networks:
  my-network:
    driver: bridge
